import type { NextPage } from 'next';
import Head from 'next/head';
import { Track } from '@/components/primitives/Track';
import { Stat } from '@/components/primitives/Stat';
import styles from '../styles/Home.module.css';
import { Heart, PlayOutline, ThumbsUp } from 'iconoir-react';
import { Heading } from '@/components/primitives/Text';
import { useUser } from '@auth0/nextjs-auth0';

const Profile: NextPage = () => {
  const { user } = useUser()

  return (
    <div className={styles.container}>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {user?.sub}
      </main>
    </div>
  );
}

export default Profile;
