import type { NextPage } from 'next';
import Head from 'next/head';
import { Track } from '@/components/primitives/Track';
import { Stat } from '@/components/primitives/Stat';
import { AlbumList, Heart, PlayOutline, ThumbsUp } from 'iconoir-react';
import { Heading } from '@/components/primitives/Text';
import { Chip } from '@/components/primitives/Chip';
import { TrackPlayer } from '@/components/primitives/TrackPlayer/TrackPlayer';
import styles from '../styles/TrackPage.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <section style={{display: "flex", flexDirection: 'column', gap: '.5rem', padding: '.5rem'}}>
          <Heading level={1}>Statistics</Heading>
          <div className={styles.statsContainer}>
            <Stat statName="Tempo" quantity={120} unit="bpm" icon={<Heart />} />
            <Stat statName="Plays" quantity={12.5} unit="M" icon={<PlayOutline />} />
            <Stat statName="Likes" quantity={51} unit="K" icon={<ThumbsUp />} />
            <Stat statName="Genres" quantity={[
              <Chip text="Ambient" key="ambient" />,
              <Chip text="EDM" key="edm" />,
              <Chip text="Anthem" key="anthem" />,
            ]} icon={<AlbumList />} />
          </div>
        </section>
        <TrackPlayer albumSource={'/../public/cant-slow-me-down.jpg'}
          trackName="Can't Slow Me Down"
          artist={['Mirani', 'LILBOI', 'GroovyRoom', 'VALORANT']} />
        {/* <TrackPlayer albumSource={'/../public/reol-agitate.jpg'}
          trackName="Agitate (煽げや尊し)"
          artist={['Reol']} /> */}
        <section  style={{display: "flex", flexDirection: 'column', gap: '.5rem', padding: '.5rem'}}>
          <Heading level={1}>People also like</Heading>
          <div style={{display: "flex", flexDirection: 'row', gap: '.5rem',}}>
            <Track artist={["Kevin Penkin"]} track="Stars"/>
            <Track artist={["Created"]} track="Artifact (Let the Music Go)"/>
            <Track artist={["Hoshimachi Suisei", "Mori Calliope"]} track="Wicked feat. Mori Calliope"/>
            <Track artist={["Moona Hoshinova"]} track="High Tide"/>
          </div>
        </section>
      </main>
    </div>
  );
}

export default Home;
